/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardEmployeeIndexRouteImport } from './routes/dashboard/employee/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardEmployeeTimeLogRouteImport } from './routes/dashboard/employee/time-log'
import { Route as DashboardAdminTasksRouteImport } from './routes/dashboard/admin/tasks'
import { Route as DashboardAdminPayrollRouteImport } from './routes/dashboard/admin/payroll'
import { Route as DashboardAdminEmployeesRouteImport } from './routes/dashboard/admin/employees'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmployeeIndexRoute = DashboardEmployeeIndexRouteImport.update({
  id: '/employee/',
  path: '/employee/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmployeeTimeLogRoute =
  DashboardEmployeeTimeLogRouteImport.update({
    id: '/employee/time-log',
    path: '/employee/time-log',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminTasksRoute = DashboardAdminTasksRouteImport.update({
  id: '/admin/tasks',
  path: '/admin/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminPayrollRoute = DashboardAdminPayrollRouteImport.update({
  id: '/admin/payroll',
  path: '/admin/payroll',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminEmployeesRoute = DashboardAdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/employees': typeof DashboardAdminEmployeesRoute
  '/dashboard/admin/payroll': typeof DashboardAdminPayrollRoute
  '/dashboard/admin/tasks': typeof DashboardAdminTasksRoute
  '/dashboard/employee/time-log': typeof DashboardEmployeeTimeLogRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/employee/': typeof DashboardEmployeeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/employees': typeof DashboardAdminEmployeesRoute
  '/dashboard/admin/payroll': typeof DashboardAdminPayrollRoute
  '/dashboard/admin/tasks': typeof DashboardAdminTasksRoute
  '/dashboard/employee/time-log': typeof DashboardEmployeeTimeLogRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/employee': typeof DashboardEmployeeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/employees': typeof DashboardAdminEmployeesRoute
  '/dashboard/admin/payroll': typeof DashboardAdminPayrollRoute
  '/dashboard/admin/tasks': typeof DashboardAdminTasksRoute
  '/dashboard/employee/time-log': typeof DashboardEmployeeTimeLogRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/employee/': typeof DashboardEmployeeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/'
    | '/dashboard/admin/employees'
    | '/dashboard/admin/payroll'
    | '/dashboard/admin/tasks'
    | '/dashboard/employee/time-log'
    | '/dashboard/admin/'
    | '/dashboard/employee/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/dashboard/admin/employees'
    | '/dashboard/admin/payroll'
    | '/dashboard/admin/tasks'
    | '/dashboard/employee/time-log'
    | '/dashboard/admin'
    | '/dashboard/employee'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/'
    | '/dashboard/admin/employees'
    | '/dashboard/admin/payroll'
    | '/dashboard/admin/tasks'
    | '/dashboard/employee/time-log'
    | '/dashboard/admin/'
    | '/dashboard/employee/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employee/': {
      id: '/dashboard/employee/'
      path: '/employee'
      fullPath: '/dashboard/employee/'
      preLoaderRoute: typeof DashboardEmployeeIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employee/time-log': {
      id: '/dashboard/employee/time-log'
      path: '/employee/time-log'
      fullPath: '/dashboard/employee/time-log'
      preLoaderRoute: typeof DashboardEmployeeTimeLogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/tasks': {
      id: '/dashboard/admin/tasks'
      path: '/admin/tasks'
      fullPath: '/dashboard/admin/tasks'
      preLoaderRoute: typeof DashboardAdminTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/payroll': {
      id: '/dashboard/admin/payroll'
      path: '/admin/payroll'
      fullPath: '/dashboard/admin/payroll'
      preLoaderRoute: typeof DashboardAdminPayrollRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/employees': {
      id: '/dashboard/admin/employees'
      path: '/admin/employees'
      fullPath: '/dashboard/admin/employees'
      preLoaderRoute: typeof DashboardAdminEmployeesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminEmployeesRoute: typeof DashboardAdminEmployeesRoute
  DashboardAdminPayrollRoute: typeof DashboardAdminPayrollRoute
  DashboardAdminTasksRoute: typeof DashboardAdminTasksRoute
  DashboardEmployeeTimeLogRoute: typeof DashboardEmployeeTimeLogRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardEmployeeIndexRoute: typeof DashboardEmployeeIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminEmployeesRoute: DashboardAdminEmployeesRoute,
  DashboardAdminPayrollRoute: DashboardAdminPayrollRoute,
  DashboardAdminTasksRoute: DashboardAdminTasksRoute,
  DashboardEmployeeTimeLogRoute: DashboardEmployeeTimeLogRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardEmployeeIndexRoute: DashboardEmployeeIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
